export const ENGLISH: Object = {
    "ActionBranchNewNode": "Creates new linked node of selected state",
    "ActionBreakApart": "Breaks links with all nodes in the graph of selected state",
    "ActionConnectToAll": "Creates links with all nodes in the graph of selected state",
    "ActionConnectToNearest": "Creates one link with the nearest node in the graph of selected state. (Notice: if there are few candidates for the connection, all the same only one of them will be connected)",
    "ActionDeleteCurrentNode": "Deletes current node",
    "Actions": "Actions",
    "Add": "Add",
    "Alphabet": "Alphabet",
    "BalancedBinTree": "Tree",
    "BornOnIteration": "Born on Iteration",
    "BranchNewNode": "Branch New Node",
    "BreakApartFromAll": "Break Apart from All",
    "BreakApartFromNearest": "Break Apart from the Nearest",
    "ChecksIfLinksCountInRange": "Condition for checking if the node's links count is in range from <FIRST_ARGUMENT> to <SECOND_ARGUMENT>",
    "ChecksIfNodeWasBornOnIterationInRange": "Condition for checking if the node was born on machine iteration in range from <FIRST_ARGUMENT> to <SECOND_ARGUMENT>. (Notice: initialized graph is zero iteration)",
    "ChecksPreviousState": "Condition for checking the state on the previous iteration",
    "Cicle": "Cicle",
    "Complete": "Complete",
    "CompleteBipartite": "Complete Bipartite",
    "Conditions": "Conditions",
    "ConnectToAll": "Connect to All",
    "ConnectToNearest": "Connect to the Nearest",
    "Faster": "Faster",
    "FromState": "From State",
    "GraphBalancedBinTree": "Generates the balanced binary tree of N levels, where the initial node is the null level",
    "GraphCicle": "Generates the cicled graph, which contains N nodes",
    "GraphComplete": "Generates the complete graph, which contains N nodes",
    "GraphCompleteBipartite": "Generates the complete bipartite graph, which contains N nodes in the first part and M in another",
    "GraphEvolution": "Graph Evolution",
    "GraphGrid": "Generates the (N x M) grid structured graph",
    "GraphGrid3": "Generates the (N x M x K) 3D-grid structured graph",
    "GraphNoLinks": "Generates the graph with N isolated nodes",
    "Grid": "Grid",
    "Grid3": "Grid 3D",
    "InitialGraph": "The Initial Graph",
    "Initialize": "Initialize the machine",
    "InitializeGraphOrMachineHere": "Initialize the Graph or the Machine here",
    "Instructions": "Instructions",
    "LinksCount": "Links Count",
    "LoadMachine": "Load The Machine",
    "MachineInstructions": "Machine Instructions",
    "NameOfPreviousState": "Name of the Previous State",
    "NoLinks": "Unlinked",
    "Pause": "Pause",
    "PreviousState": "Previous State",
    "Slower": "Slower",
    "Start": "Start",
    "TerminatedAllNodesDeleted": "THE MACHINE IS TERMINATED\nAll nodes are removed",
    "TerminatedAllNodesSetStopState": "THE MACHINE IS TERMINATED\nAll nodes changed their states to \"stop\"",
    "ToState": "To State"
}